Param (
	[Parameter(Mandatory=$True)]
    [string]$solutionId,
    [Parameter(Mandatory=$True)]
    [string]$environment,
	[Parameter(Mandatory=$True)]
    [string]$resourceGroupName
)


$ErrorActionPreference = "Stop"

##############################################
# Import utility functions
##############################################
. ".\deploy.utilities.ps1"
. ".\deploy.servicebus.ps1"

##############################################
# Remove non-alpha-numeric characters
##############################################
$solutionId = $solutionId.ToLower() -replace "\W"
$environment = $environment.ToLower() -replace "\W"

##############################################
# Set default resource group and location
##############################################
Set-Default-Resource-Group -resourceGroupName $resourceGroupName

# Enable Microsoft.EventGrid in the subscription if it isn't already registered
az provider register --namespace Microsoft.EventGrid

##############################################
# Get Integration Platform configuration from JSON
# Note: JSON is generated by running: dis-cli config-export
##############################################

$configPath = "platform-config.json"
if (-not (Test-Path $configPath)) {
    Write-Error "Platform configuration file not found: $configPath. Run 'dis-cli config-export' first."
    exit 1
}

$config = Get-Content $configPath | ConvertFrom-Json

$brokerId = $config.brokerId
$resolverId = $config.resolverId
$managerId = $config.managerId
$continuationId = $config.continuationId
$eventId = $config.eventId
$retryId = $config.retryId

$nameOfTo = $config.userPropertyNames.to
$nameOfFrom = $config.userPropertyNames.from
$nameOfEventId = $config.userPropertyNames.eventId

##############################################
# Define names Azure resource names
##############################################
$sbNamespace = "sb-{0}-{1}" -f $solutionId, $environment

##############################################
# Install Azure CLI extensions
##############################################

Try {
    Add-Extension -name application-insights
}
Catch {
    if($_.Exception.Message -eq "WARNING: Extension 'application-insights' is already installed.")
    {
        Write-Host "Extension 'application-insights' is already installed."
    }
    else
    {
        throw
    }
}

##############################################
# Delete Obsolete Topics
##############################################

$obsoleteTopics = New-Object System.Collections.ArrayList

$topics = New-Object System.Collections.ArrayList

$topics.Add($resolverId) > $null
$topics.Add($brokerId) > $null
$topics.Add($managerId) > $null
$topics.Add($eventId) > $null

foreach ($endpoint in $config.endpoints) {
    $topics.Add($endpoint.id) > $null
}

$existingTopics = az servicebus topic list `
    --namespace-name $sbNamespace `
    --resource-group $resourceGroupName
    | ConvertFrom-Json

foreach($existingTopic in $existingTopics){
    If($topics -notcontains $existingTopic.name){
        $obsoleteTopics.Add($existingTopic.name) > $null
    }
}

foreach($obsoleteTopic in $obsoleteTopics){
    Write-Host 'Deleting topic '$obsoleteTopic
    #az servicebus topic delete `
    #    --namespace-name $sbNamespace `
    #    --resource-group $resourceGroupName `
    #    --name $obsoleteTopic
}

Write-Host 'Done Deleting obsolete Topics'

##############################################
# Delete Obsolete Subscriptions on endpointTopics
##############################################

foreach($endpoint in $config.endpoints){
    $obsoleteforwardSubscriptions = New-Object System.Collections.ArrayList

    $existingSubscriptions = az servicebus topic subscription list `
    --namespace-name $sbNamespace `
    --resource-group $resourceGroupName `
    --topic-name $endpoint.id
    | ConvertFrom-Json

    $forwardSubscriptions = New-Object System.Collections.ArrayList
    $forwardSubscriptions.Add($brokerId) > $null
    $forwardSubscriptions.Add($ContinuationId) > $null
    $forwardSubscriptions.Add($resolverId) > $null
    $forwardSubscriptions.Add($retryId) > $null
    $forwardSubscriptions.Add($endpoint.id) > $null

    foreach($forwardSub in $existingSubscriptions){
        if($forwardSub -ne $null){
            if($forwardSubscriptions -notcontains $forwardSub.name){
                $obsoleteforwardSubscriptions.Add($forwardSub.name) > $null
            }
        }
    }

    #Delete obsolete subscriptions on endpointTopics
    foreach($fwsub in $obsoleteforwardSubscriptions){
        Write-Host 'Deleting subscription' $fwsub 'on' $endpoint.id
        az servicebus topic subscription delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $endpoint.id `
            --name $fwsub
    }
}

Write-Host 'Done Deleting obsolete endpoint subscriptions'

##############################################
# Delete Obsolete Subscriptions on systemTopics
##############################################
#Manager
$managerExistingSubscriptions = az servicebus topic subscription list `
    --namespace-name $sbNamespace `
    --resource-group $resourceGroupName `
    --topic-name $managerId
    | ConvertFrom-Json


$manSubs = New-Object System.Collections.ArrayList
$manSubs.Add($brokerId) > $null
foreach($endpoint in $config.endpoints){
    $manSubs.Add($endpoint.id) > $null
}

foreach($manExSub in $managerExistingSubscriptions){
    If($manSubs -notcontains $manExSub.name){
        Write-Host 'Deleting manager-topic subscription'$manExSub.name
        az servicebus topic subscription delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $managerId `
            --name $manExSub.name
    }
}

#Broker
$brokerExistingSubscriptions = az servicebus topic subscription list `
    --namespace-name $sbNamespace `
    --resource-group $resourceGroupName `
    --topic-name $brokerId
    | ConvertFrom-Json

$brokerSubs = New-Object System.Collections.ArrayList
$brokerSubs.Add($brokerId) > $null
$brokerSubs.Add($resolverId) > $null
foreach($endpoint in $config.endpoints){
    $brokerSubs.Add($endpoint.id) > $null
}

foreach($brokerExSub in $brokerExistingSubscriptions){
    If($brokerSubs -notcontains $brokerExSub.name){
        Write-Host 'Deleting broker-topic subscription' $brokerExSub.name
        az servicebus topic subscription delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $brokerId `
            --name $brokerExSub.name
    }
}

Write-Host 'Done Deleting obsolete Subscriptions'

##############################################
# Delete Obsolete Subscriptions Rules on EndpointSubscriptions
##############################################

foreach($endpoint in $config.endpoints){
    #Get all subscription rules on topics named after endpoints
    $topicSubscriptionRules = az servicebus topic subscription rule list `
        --namespace-name $sbNamespace `
        --resource-group $resourceGroupName `
        --topic-name $endpoint.id `
        --subscription-name $endpoint.id
        | ConvertFrom-Json

    $obsoleteEndpointSups = New-Object System.Collections.ArrayList
    foreach($subRule in $topicSubscriptionRules){
        $subRuleName = $endpoint.id
        If($subRule.name -ne "to-$subRuleName"){
            Write-Host 'EndpointSubRule' $subRule.name 'not equal '"to-$subRuleName"
            $obsoleteEndpointSups.Add($subRule.name) > $null
            az servicebus topic subscription rule delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $endpoint.id `
            --subscription-name $endpoint.id `
            --name $subRule.name
        }
    }

    $brokerSubscriptionRules = az servicebus topic subscription rule list `
        --namespace-name $sbNamespace `
        --resource-group $resourceGroupName `
        --topic-name $endpoint.id `
        --subscription-name $brokerId
        | ConvertFrom-Json

    foreach($brokerSubRule in $brokerSubscriptionRules){
        $subRuleName = $endpoint.id
        If($brokerSubRule.name -ne "from-$subRuleName"){
            Write-Host 'brokerSubRule ' $brokerSubRule.name 'not equal '"from-$subRuleName"
            az servicebus topic subscription rule delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $endpoint.id `
            --subscription-name $brokerId `
            --name $brokerSubRule.name
        }
    }

    $contSubscriptionRules = az servicebus topic subscription rule list `
        --namespace-name $sbNamespace `
        --resource-group $resourceGroupName `
        --topic-name $endpoint.id `
        --subscription-name $continuationId
        | ConvertFrom-Json

    foreach($contSubRule in $contSubscriptionRules){
        If($contSubRule.name -ne "$continuationId"){
            Write-Host 'continuationSubRule ' $contSubRule.name 'not equal '"$continuationId"
            az servicebus topic subscription rule delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $endpoint.id `
            --subscription-name $continuationId `
            --name $contSubRule.name
        }
    }

    $resolverSubscriptionRules = az servicebus topic subscription rule list `
        --namespace-name $sbNamespace `
        --resource-group $resourceGroupName `
        --topic-name $endpoint.id `
        --subscription-name $resolverId
        | ConvertFrom-Json

    foreach($resSubRule in $resolverSubscriptionRules){
        $subRuleName = $endpoint.id
        If($resSubRule.name -ne "from-$subRuleName"){
            If($resSubRule.name -ne "to-$subRuleName"){
                Write-Host 'ResolverSubRule' $resSubRule.name 'not equal '"to-$subRuleName" 'or' "from-$subRuleName"
                az servicebus topic subscription rule delete  `
                --namespace-name $sbNamespace `
                --resource-group $resourceGroupName `
                --topic-name $endpoint.id `
                --subscription-name $resolverId `
                --name $resSubRule.name
            }
        }
    }



    $retrySubscriptionRules = az servicebus topic subscription rule list `
        --namespace-name $sbNamespace `
        --resource-group $resourceGroupName `
        --topic-name $endpoint.id `
        --subscription-name $retryId
        | ConvertFrom-Json

    foreach($retrySubRule in $retrySubscriptionRules){
        If($retrySubRule.name -ne $retryId){
            Write-Host 'retrytSubRule ' $retrySubRule.name 'not equal'"$retryId"
            az servicebus topic subscription rule delete  `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $endpoint.id `
            --subscription-name $retryId `
            --name $retrySubRule.name
        }
    }
}

#System topic subscription
#broker
foreach($endpoint in $config.endpoints){
    If($endpoint.eventTypesConsumed.Count -ne 0){
        $brokerTopicEndpointSubscriptionRules = az servicebus topic subscription rule list `
            --namespace-name $sbNamespace `
            --resource-group $resourceGroupName `
            --topic-name $brokerId `
            --subscription-name $endpoint.id
            | ConvertFrom-Json

        $eventTypesConsumed = New-Object System.Collections.ArrayList
        $endpointId = $endpoint.id
        $eventTypesConsumed.Add("to-$endpointId") > $null
        foreach($event in $endpoint.eventTypesConsumed){
            $eventTypesConsumed.Add($event.id) > $null
        }

        foreach($brokerEndpointrule in $brokerTopicEndpointSubscriptionRules){
            $endpointId = $endpoint.id
            If($eventTypesConsumed -notcontains $brokerEndpointrule.name){
                Write-Host 'broker topic endpoint' $endpointId 'sub: '$brokerEndpointrule.name 'not in EventTypesConsumed'
                az servicebus topic subscription rule delete  `
                    --namespace-name $sbNamespace `
                    --resource-group $resourceGroupName `
                    --topic-name $brokerId `
                    --subscription-name $endpoint.id `
                    --name $brokerEndpointrule.name
            }
        }
    }
}

#manager
foreach($endpoint in $config.endpoints){
    $managerTopicEndpointSubscriptionRules = az servicebus topic subscription rule list `
        --namespace-name $sbNamespace `
        --resource-group $resourceGroupName `
        --topic-name $managerId `
        --subscription-name $endpoint.id
        | ConvertFrom-Json

    foreach($managerEndpointrule in $managerTopicEndpointSubscriptionRules){
        $endpointId = $endpoint.id
        If($managerEndpointrule.name -ne "to-$endpointId"){
            Write-Host 'manager topic endpoint sub: '$managerEndpointrule.name 'not equal' "to-$endpointId"
            az servicebus topic subscription rule delete  `
                --namespace-name $sbNamespace `
                --resource-group $resourceGroupName `
                --topic-name $managerId `
                --subscription-name $endpoint.id `
                --name $managerEndpointrule.name
        }
    }
}

