Param (
	[Parameter(Mandatory=$True)]
    [string]$solutionId,
    [Parameter(Mandatory=$True)]
    [string]$environment,
	[Parameter(Mandatory=$True)]
    [string]$resourceGroupName
)

$ErrorActionPreference = "Stop"

##############################################
# Import utility functions
##############################################
. ".\deploy.utilities.ps1"
. ".\deploy.servicebus.ps1"

##############################################
# Get Integration Platform configuration from JSON
# Note: JSON is generated by running: dis-cli config-export
##############################################

$configPath = "platform-config.json"
if (-not (Test-Path $configPath)) {
    Write-Error "Platform configuration file not found: $configPath. Run 'dis-cli config-export' first."
    exit 1
}

$config = Get-Content $configPath | ConvertFrom-Json

$sbNamespace = "sb-{0}-{1}" -f $solutionId, $environment

foreach ($endpoint in $config.endpoints) {
    foreach ($roleAssignment in $endpoint.roleAssignments) {
        if ($roleAssignment.environment -eq $Environment)
        {
            Write-Host "AssigneeId:" $roleAssignment.principalId
            Assign-ServiceBusTopicSender -assigneeId $roleAssignment.principalId -serviceBusNamespace $sbNamespace -topic $endpoint.id -resourceGroupName $resourceGroupName
            Assign-ServiceBusSubscriptionReader -assigneeId $roleAssignment.principalId -serviceBusNamespace $sbNamespace -topic $endpoint.id -subscription $endpoint.id -resourceGroupName $resourceGroupName
        }
    }
}