$ErrorActionPreference = "Stop"

##############################################
# Get Integration Platform configuration from JSON
# Note: JSON is generated by running: dis-cli config-export
##############################################

$configPath = "platform-config.json"
if (-not (Test-Path $configPath)) {
    Write-Error "Platform configuration file not found: $configPath. Run 'dis-cli config-export' first."
    exit 1
}

$config = Get-Content $configPath | ConvertFrom-Json

$brokerId = $config.brokerId
$resolverId = $config.resolverId
$managerId = $config.managerId
$eventId = $config.eventId

echo "##vso[task.setvariable variable=broker_id;isOutput=true]$($brokerId.ToLower())"
echo "##vso[task.setvariable variable=resolver_Id;isOutput=true]$($resolverId.ToLower())"
echo "##vso[task.setvariable variable=event_id;isOutput=true]$($eventId.ToLower())"
echo "##vso[task.setvariable variable=manager_id;isOutput=true]$($managerId.ToLower())"

$endpoints = @{}

foreach ($endpoint in $config.endpoints) {
    $endpointId = $endpoint.id.ToLower()
    if($endpoint.eventTypesConsumed.Count -ne 0) {
        $eventTypes = @($endpoint.eventTypesConsumed)
        $counter = 0
        foreach ($eventType in $eventTypes) {
            $eventTypes[$counter] = $eventType.id.ToLower()
            $counter = $counter + 1
        }

        if($eventTypes.Count -eq 1) {
            $endpoints[$endpointId] = ,$eventTypes
        }
        else {
            $endpoints[$endpointId] = $eventTypes
        }
    }
}

$counter = 0
$endpointIds = @($config.endpoints.id)
foreach ($endpointId in $endpointIds) {
    $endpointIds[$counter] = $endpointId.ToLower()
    $counter = $counter + 1
}

$json = ($endpoints | ConvertTo-Json -Compress)

Write-Host $endpointIds
Write-Host $json

echo "##vso[task.setvariable variable=platform_eventtypes_json;isOutput=true]$json"
echo "##vso[task.setvariable variable=platform_endpoints;isOutput=true]$endpointIds"