using NimBus.Core.Events;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace NimBus.Events.Notifications
{
    [Description("Published when a customer-facing notification has been sent.")]
    public class CustomerNotified : Event
    {
        public static readonly CustomerNotified Example = new CustomerNotified
        {
            OrderId = Guid.Parse("2bb7d0b3-840f-4e54-a0d4-fb31a7cabf82"),
            NotificationId = Guid.Parse("990d2e35-11c0-4b6d-8c08-6d61c95f9d31"),
            Template = "shipment-update",
            Channel = "email",
            SentAt = DateTime.UtcNow,
        };

        [Required]
        [Description("The order this notification relates to.")]
        public Guid OrderId { get; set; }

        [Required]
        [Description("The notification identifier generated by the delivery service.")]
        public Guid NotificationId { get; set; }

        [Required]
        [Description("The notification template or use case that was sent.")]
        public string Template { get; set; }

        [Required]
        [Description("The outbound channel, such as email or sms.")]
        public string Channel { get; set; }

        [Description("The UTC timestamp when the notification was sent.")]
        public DateTime SentAt { get; set; }

        public override string GetSessionId() => OrderId.ToString();
    }
}
